name: Bazel CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md

jobs:

  bazel:
    name: Bazel
    runs-on: ubuntu-latest
    steps:
      - name: Bazel RC
        run: |
          echo "build --config=ci" >> ~/.bazelrc
          echo "build --disk_cache=${{runner.temp}}/bazel.disk" >> ~/.bazelrc
      - uses: actions/cache@v4
        with:
          path: ${{runner.temp}}/bazel.disk
          key: bazel
      - uses: actions/checkout@v4
      - name: Bazel Test
        run: bazel test ...
      - name: Work around https://github.com/actions/upload-artifact/issues/92
        run: echo "bazel_out=$(bazel info output_path)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{env.bazel_out}}/*/testlogs/**
      - run: bazel shutdown
